### ISSUE TITLE
UDDDIOOO

### ISSUE THREAD

**Issue by ncvescera** [crilose/spericolatoBot#1]
Il codice non è fantastico. MALE!
Io  lo migliorerei !

**Comment by crilose** [comment]
Vescera per cortesia si tratta di un bot di VASCO ROSSI.
Come pretendi che un bot di VASCO ROSSI sia ordinato e preciso?

**Comment by ncvescera** [comment]
Andiamo !!!
Qualsiasi codice che scrivi va fatto per bene !!!!

**Comment by crilose** [comment]
Hai ragione, appena avrò sbatti per prima cosa eliminerò le condizioni ridondanti.

**Comment by ncvescera** [comment]
Direi che questa issue può anche essere chiusa !
